/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as PortalSubmitRouteImport } from './routes/portal.submit'
import { Route as PortalSitesRouteImport } from './routes/portal.sites'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalSubmitRoute = PortalSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSitesRoute = PortalSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/sites': typeof PortalSitesRoute
  '/portal/submit': typeof PortalSubmitRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/sites': typeof PortalSitesRoute
  '/portal/submit': typeof PortalSubmitRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/tags': typeof AdminTagsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/sites': typeof PortalSitesRoute
  '/portal/submit': typeof PortalSubmitRoute
  '/site/$slug': typeof SiteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/portal'
    | '/reset-password'
    | '/sitemap.xml'
    | '/submit'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/seo'
    | '/admin/sites'
    | '/admin/tags'
    | '/portal/billing'
    | '/portal/sites'
    | '/portal/submit'
    | '/site/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/portal'
    | '/reset-password'
    | '/sitemap.xml'
    | '/submit'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/seo'
    | '/admin/sites'
    | '/admin/tags'
    | '/portal/billing'
    | '/portal/sites'
    | '/portal/submit'
    | '/site/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/portal'
    | '/reset-password'
    | '/sitemap.xml'
    | '/submit'
    | '/admin/approvals'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/members'
    | '/admin/messages'
    | '/admin/seo'
    | '/admin/sites'
    | '/admin/tags'
    | '/portal/billing'
    | '/portal/sites'
    | '/portal/submit'
    | '/site/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/submit': {
      id: '/portal/submit'
      path: '/submit'
      fullPath: '/portal/submit'
      preLoaderRoute: typeof PortalSubmitRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/sites': {
      id: '/portal/sites'
      path: '/sites'
      fullPath: '/portal/sites'
      preLoaderRoute: typeof PortalSitesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminTagsRoute: typeof AdminTagsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContactRoute: AdminContactRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminTagsRoute: AdminTagsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalRouteChildren {
  PortalBillingRoute: typeof PortalBillingRoute
  PortalSitesRoute: typeof PortalSitesRoute
  PortalSubmitRoute: typeof PortalSubmitRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalBillingRoute: PortalBillingRoute,
  PortalSitesRoute: PortalSitesRoute,
  PortalSubmitRoute: PortalSubmitRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
